# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# This is a basic workflow to help you get started with Actions
name: CI
# Controls when the action will run. 
on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js lts/Hydrogen
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/Hydrogen'
        cache: 'npm'
#     - name: Install Deps
#       run: npm ci
#     - name: Create production build
#       run: npm run build
    - name: Copy repo to remote host
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: .
        target: ~/event-commitee-kartjis
        strip_components: 1
    - name: Restart pm2 instance
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: cd ~/event-commitee-kartjis && npm ci && npm run build && pm2 restart event-commitee-kartjis
